#服务端口
server:
  port: 8002
#服务名
spring:
  application:
    name: service-oss
  #环境设置
  profiles:
    active: dev
  servlet:
    multipart:
      #最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      #最大总上传数据大小：默认1M
      max-request-size: 1024MB
#阿里云oss配置
aliyun:
  bucketName: langju-online
  accessKeyId: 
  accessKeySecret: 
  #OSS对应的区域
  endpoint: oss-cn-beijing.aliyuncs.com

